# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_remove_myuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
