# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, to='rsvp.Guest'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owners',
            field=models.ManyToManyField(blank=True, to='rsvp.Owner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='rsvp.Vendor'),
        ),
    ]
